---
- hosts: all
  remote_user: root
  gather_facts: no
  vars:
    SERVER_HOSTNAME: #Insert desired hostname for server
    HOST_IP:         #Insert desired ip for host here
    HOST_SUBNET:     #Insert subnet mask for host here
    HOST_GATEWAY:    #Insert gateway for host here
  vars_files:
    - external_vars.yml

  roles:
    - packages
    - configs

  tasks:
  - name: Restart server
    command: /sbin/shutdown -r +1
    async: 0
    poll: 0
    ignore_errors: true

  handlers:
    - name: restart sshd
      service:
        name: sshd
        state: restarted
