---
- hosts: all
  remote_user: root
  gather_facts: no
  vars_files:
    - external_vars.yml

  roles:
    - packages
    - configs

  tasks:
  - name: Restart server
    command: /sbin/shutdown -r +1
    async: 0
    poll: 0
    ignore_errors: true
