---
# tasks file for packages
#Installs list of desired packages on new host
- name: Install epel and scl repos prior to desired packages 
  yum:
    name:
      - epel-release
      - centos-release-scl
    state: latest
 
- name: Install a list of packages
  yum:
    name: 
      - parted
      - libselinux-python
      - net-tools
      - lsscsi
      - nmap
      - wget
      - htop
      - curl
      - open-vm-tools
      - git
    state: latest

- name: Ensures all installed packages are up to date
  yum:
    name: '*'
    state: latest
