---
# tasks file for packages
#Installs list of desired packages on new host
- name: Disable selinux via command to allow the use of copy
  command: "/usr/sbin/setenforce 0"

- name: 
  dnsset: 

- name: Install centos, epel and scl repos prior to desired packages 
  yum:
    name:
      - centos-release
      - epel-release
      - centos-release-scl
    state: latest
 
- name: Install a list of packages
  yum:
    name: 
      - parted
      - libselinux-python
      - net-tools
      - lsscsi
      - nmap
      - wget
      - htop
      - curl
      - open-vm-tools
      - git
    state: latest

- name: Ensures all installed packages are up to date
  yum:
    name: '*'
    state: latest
