---
# tasks file for minecraft
- name: add required port for server
  firewalld:
    port: 25565/tcp
    permanent: yes
    state: enabled

- name: Install openjdk 
  yum:
    name: 
      - java-1.8.0-openjdk
    state: latest

- name: Create a directory for the minecraft files under opt
  file:
    path: /opt/minecraft/
    state: directory

#Add the following variable to your encrypted vault file!!
- name: Add an account to run the server as
  user:
    name: "{{ MINECRAFT_USER }}"
    shell: /bin/bash
    home: /opt/minecraft/

- name: Change permisisons on app directory
  file:
    path: /opt/minecraft/
    state: directory
    owner: "{{ MINECRAFT_USER }}"
    mode: '0755'

- name: Download server jar with md5 check
  get_url:
    url: https://launcher.mojang.com/v1/objects/3dc3d84a581f14691199cf6831b71ed1296a9fdf/server.jar
    dest: /opt/minecraft/server.jar

- name: Accept the eula 
  copy:
    content: 'eula=true'
    dest: /opt/minecraft/eula.txt 

#Note: Add a SERVER_RAM for the service template 
- name: Genereate template for systemd service
  template:
    src: service.j2
    dest: /etc/systemd/system/minecraft.service

- name: Start and enable minecraft server service 
  service:
    name: minecraft
    state: started
    enabled: yes
