---
# tasks file for configs
#
- name: Add hostname to new server
  hostname:
    name: "{{ SERVER_HOSTNAME }}"

- name: Put SELinux in permissive mode, logging actions that would be blocked.
  selinux:
    policy: targeted
    state: permissive

- name: Add desired ssh port to config
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^Port 22"
    line: "Port {{ sshdport }}"
    insertafter: "^# What "
    state: present
  notify:
    - restart sshd

- name: set PermitRootLogin to no
  lineinfile:
    path: /etc/ssh/sshd_config
    insertafter: "^#PermitRootLogin without-password"
    line: "PermitRootLogin no"
    state: present
  notify:
    - restart sshd

- name: Add a maintenace account with full sudo 
  user:
    name: "{{ service_account }}"
    shell: /bin/bash
    groups: wheel
    append: yes

- name: Create a symbolic link to remove consistent network device naming
  file:
    src: /dev/null
    dest: /etc/udev/rules.d/80-net-name-slot.rules
    state: link

- name: Validate the sudoers file before saving
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL' 
    validate: /usr/sbin/visudo -cf /etc/sudoers 

- name: Disable ipv6 on the host
  lineinfile:
    path: /etc/sysctl.conf
    line: 'net.ipv6.conf.all.disable_ipv6 = 1'

- name: Disable ipv6 on the host 2
  lineinfile:
    path: /etc/sysctl.conf
    line: 'net.ipv6.conf.default.disable_ipv6 = 1'
