---
# tasks file for configs
#
- name: Put SELinux in permissive mode, logging actions that would be blocked.
  selinux:
    policy: targeted
    state: permissive

- name: Add desired ssh port to config
lineinfile: dest="/etc/ssh/sshd_config" regexp="^Port 22" line="Port {{ sshdport }}" insertafter="^# What " state=present
notify:
- restart sshd

– name: set PermitRootLogin to no
lineinfile: dest="/etc/ssh/sshd_config" insertafter="^#PermitRootLogin without-password" line="PermitRootLogin no" state=present
- restart sshd

- name: Add a maintenace account with full sudo 
  user:
    name: {{ service_account }} 
    shell: /bin/bash
    groups: wheel
    append: yes

# NOTE: Fully quoted because of the ': ' on the line. See the Gotchas in the YAML docs.
- name: Validate the sudoers file before saving
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp='^%wheel'
    line='%wheel ALL=(ALL) NOPASSWD: ALL'"
    validate: /usr/sbin/visudo -cf %s

- name: Create a symbolic link to remove consistent network device naming
  file:
    src: /dev/null
    dest: /etc/udev/rules.d/80-net-name-slot.rules
    state: link

handlers:
  - name: restart sshd
    service:
      name: sshd
      state: restarted	
